services:
  caddy:
    image: caddy:latest
    container_name: caddy
    env_file:
      - .env
      - ./hashes/.env.caddy # Use the generated hashed passwords
    networks:
      caddy-net:
        ipv4_address: 10.2.0.2
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./config/caddy_data:/data
      - ./config/caddy_config:/config

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "" # Auth by Caddy
      FTLCONF_LOCAL_IPV4: "10.2.0.100"
    networks:
      caddy-net:
        ipv4_address: 10.2.0.100
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "8081:80/tcp"
    volumes:
      - './config/pihole/etc-pihole:/etc/pihole'
      - './config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './config/pihole/etc-lighttpd/external.conf:/etc/lighttpd/external.conf'
    restart: unless-stopped
    depends_on:
      - caddy

  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    env_file:
      - .env
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi, ja, si)
      - LANG=en

      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WIREGUARD_VPN_SUBDOMAIN}.${DOMAIN}

      # Optional:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_a_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      - WG_DEFAULT_ADDRESS=10.8.0.x  # Checked by Caddy to determine internal vs external
      - WG_DEFAULT_DNS=10.2.0.100
      - WG_POST_UP=echo "iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; \
        iptables -A FORWARD -i wg0 -j ACCEPT; \
        iptables -A FORWARD -o wg0 -j ACCEPT; \
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -d 10.2.0.0/24 -j RETURN; \
        iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE;" > /etc/wireguard/post-up.txt
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_a_bcrypt_hash.md" for generate the hash)

    volumes:
      - ./config/wg-easy:/etc/wireguard

    networks:
      - caddy-net

    ports:
      - "51820:51820/udp"  # WireGuard Port
      - "51821:51821/tcp"  # wg-easy Web Interface

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  caddy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24
