services:
  caddy:
    image: caddy:latest
    container_name: caddy
    env_file:
      - .env
      - ./hashes/.env.caddy # Use the generated hashed passwords
    networks:
      caddy-net:
        ipv4_address: 192.168.100.2
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./config/caddy_data:/data
      - ./config/caddy_config:/config

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - .env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "" # Auth by Caddy
      FTLCONF_LOCAL_IPV4: "192.168.100.100"
    networks:
      caddy-net:
        ipv4_address: 192.168.100.100
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "8081:80/tcp"
    volumes:
      - './config/pihole/etc-pihole:/etc/pihole'
      - './config/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './config/pihole/etc-lighttpd/external.conf:/etc/lighttpd/external.conf'
    restart: unless-stopped
    depends_on:
      - caddy

  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    env_file:
      - .env
    environment:
      # Change Language:
      - LANG=en

      # Required:
      - WG_HOST=${WIREGUARD_VPN_SUBDOMAIN}.${DOMAIN}

      # Optional:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=192.168.100.100
    volumes:
      - ./config/wg-easy:/etc/wireguard

    ports:
      - "51820:51820/udp"  # WireGuard Port
      - "51821:51821/tcp"  # wg-easy Web Interface
    network_mode: "service:caddy"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  caddy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
