include:
  - path: './containers/caddy/docker-compose.yml'
  - path: './containers/wg-easy/docker-compose.yml'
  - path: './containers/pihole/docker-compose.yml'

networks:
  caddy-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.2.0.0/24