services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - ../../.env
    dns:
      - 1.1.1.1
      - 8.8.8.8
    environment:
      TZ: "${TZ}"
      WEBPASSWORD: "" # Auth by Caddy
      FTLCONF_LOCAL_IPV4: "pihole"
    networks:
      caddy-net:
        ipv4_address: 10.2.0.100
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp"
      - "8081:80/tcp"
    volumes:
      - './pihole/etc-pihole:/etc/pihole'
      - './pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
      - './pihole/etc-lighttpd/external.conf:/etc/lighttpd/external.conf'
    restart: unless-stopped
    depends_on:
      - caddy

networks:
  caddy-net:
    external: true