services:
  caddy:
    image: caddy:latest
    container_name: caddy
    env_file:
      - ../../.env
      - ../../hashes/.env.caddy # Use the generated hashed passwords
    networks:
     - caddy-net
    restart: unless-stopped
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    volumes:
      - ../../Caddyfile:/etc/caddy/Caddyfile:ro
      - ../config/caddy_data:/data
      - ../config/caddy_config:/config

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false

networks:
  caddy-net:
    external: true