services:
  wg-easy:
    container_name: wg-easy
    image: ghcr.io/wg-easy/wg-easy:latest
    env_file:
      - ../../.env
    environment:
      # Change Language:
      # (Supports: en, ua, ru, tr, no, pl, fr, de, ca, es, ko, vi, nl, is, pt, chs, cht, it, th, hi, ja, si)
      - LANG=en

      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=${WIREGUARD_VPN_SUBDOMAIN}.${DOMAIN}

      # Optional:
      - PASSWORD_HASH=$$2y$$10$$hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R/pIelfEMYyG # (needs double $$, hash of 'foobar123'; see "How_to_generate_a_bcrypt_hash.md" for generate the hash)
      # - PORT=51821
      # - WG_PORT=51820
      # - WG_CONFIG_PORT=92820
      - WG_DEFAULT_ADDRESS=10.8.0.x  # Checked by Caddy to determine internal vs external
      - WG_DEFAULT_DNS=172.19.0.7
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PERSISTENT_KEEPALIVE=25
      # Custom iptables Rules
      - WG_POST_UP=iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -d 172.19.0.0/24 -j RETURN; \
                   iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; \
                   iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT; \
                   iptables -A FORWARD -i wg0 -j ACCEPT; \
                   iptables -A FORWARD -o wg0 -j ACCEPT;
      # Clean up iptables rules when WireGuard stops
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -d 172.19.0.0/24 -j RETURN; \
                     iptables -t nat -D POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE; \
                     iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT; \
                     iptables -D FORWARD -i wg0 -j ACCEPT; \
                     iptables -D FORWARD -o wg0 -j ACCEPT;
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
      # - UI_TRAFFIC_STATS=true
      # - UI_CHART_TYPE=0 # (0 Charts disabled, 1 # Line chart, 2 # Area chart, 3 # Bar chart)
      # - WG_ENABLE_ONE_TIME_LINKS=true
      # - UI_ENABLE_SORT_CLIENTS=true
      # - WG_ENABLE_EXPIRES_TIME=true
      # - ENABLE_PROMETHEUS_METRICS=false
      # - PROMETHEUS_METRICS_PASSWORD=$$2a$$12$$vkvKpeEAHD78gasyawIod.1leBMKg8sBwKW.pQyNsq78bXV3INf2G # (needs double $$, hash of 'prometheus_password'; see "How_to_generate_a_bcrypt_hash.md" for generate the hash)

    volumes:
      - etc_wireguard:/etc/wireguard

    ports:
      - "51820:51820/udp"  # WireGuard Port
      - "51821:51821/tcp"  # wg-easy Web Interface

    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

    networks:
      wireguard-net:
        ipv4_address: 172.21.0.2
      caddy-net:
        ipv4_address: 172.19.0.8

volumes:
  etc_wireguard:
    external: false
